version: '3.4'

services:
  exporter:
    restart: always
    environment:
      - GITHUB_EXPORTER_LOG_LEVEL=debug
      - GITHUB_EXPORTER_LOG_PRETTY=true
      - GITHUB_EXPORTER_WEB_PPROF=true
      - GITHUB_EXPORTER_TOKEN=${GITHUB_EXPORTER_TOKEN}
      - GITHUB_EXPORTER_ORGS=${GITHUB_EXPORTER_ORGS}
      - GITHUB_EXPORTER_REPOS=${GITHUB_EXPORTER_REPOS}
      - GITHUB_EXPORTER_COLLECTOR_ORGS=true
      - GITHUB_EXPORTER_COLLECTOR_REPOS=true
      - GITHUB_EXPORTER_COLLECTOR_BILLING=${GITHUB_EXPORTER_COLLECTOR_BILLING:-true}
      - GITHUB_EXPORTER_COLLECTOR_WORKFLOW_RUNS=${GITHUB_EXPORTER_COLLECTOR_WORKFLOW_RUNS:-true}
      - GITHUB_EXPORTER_COLLECTOR_WORKFLOW_JOBS=${GITHUB_EXPORTER_COLLECTOR_WORKFLOW_JOBS:-true}
      - GITHUB_EXPORTER_COLLECTOR_RUNNERS=${GITHUB_EXPORTER_COLLECTOR_RUNNERS:-true}
    ports:
      - ${GITHUB_EXPORTER_WEB_ADDRESS:-9504}:9504
