#:schema https://mise.jdx.dev/schema/mise.json

[tools]
cosign = "3.1.3"
go = "1.26.6"
golangci-lint = "2.12.2"
goreleaser = "2.17.1"
hugo-extended = "0.165.0"
pre-commit = "4.6.2"
task = "3.52.0"

"github:cloudsmith-io/cloudsmith-cli" = "1.22.0"
