module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/Masterminds/sprig/v3 v3.1.0 // indirect
	github.com/google/uuid v1.1.2 // indirect
	github.com/huandu/xstrings v1.3.2 // indirect
	github.com/imdario/mergo v0.3.11 // indirect
	github.com/mitchellh/reflectwalk v1.0.1 // indirect
	github.com/restic/calens v0.2.0
	golang.org/x/crypto v0.0.0-20201016220609-9e8e0b390897 // indirect
)
