module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	golang.org/x/lint v0.0.0-20200302205851-738671d3881b // golint
	golang.org/x/tools v0.0.0-20201028111035-eafbe7b904eb // indirect
)
