module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/haya14busa/goverage v0.0.0-20180129164344-eec3514a20b5
	golang.org/x/tools v0.0.0-20201028111035-eafbe7b904eb // indirect
)
