module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/cespare/reflex v0.3.0
	github.com/fsnotify/fsnotify v1.4.9 // indirect
	golang.org/x/sys v0.0.0-20201028094953-708e7fb298ac // indirect
)
