module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	golang.org/x/tools v0.0.0-20201028111035-eafbe7b904eb // indirect
	honnef.co/go/tools v0.0.1-2020.1.6 // cmd/staticcheck
)
