---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: release

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup nodejs
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          private-key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write
          permission-packages: write

      - name: Checkout source
        uses: actions/checkout@v7
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Write buildtime
        run: date >| .github/RELEASE

      - name: Install releaser
        run: |
          npm install -g \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github \
            semantic-release-replace-plugin \
            conventional-changelog-conventionalcommits@9

      - name: Run releaser
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: semantic-release

      - name: Source rebase
        run: git pull --autostash --rebase

      - name: Commit changes
        uses: EndBug/add-and-commit@v11
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: .github/RELEASE
          message: "docs: automated release update [skip ci]"
          push: true
          commit: --signoff

...
